.TH "add_test_cases.NumpyArrayEncoder" 3 "Version 1" "DD2358 HPC Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
add_test_cases.NumpyArrayEncoder
.SH SYNOPSIS
.br
.PP
.PP
Inherits JSONEncoder\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdefault\fP (self, obj)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for DD2358 HPC Project from the source code\&.
